// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: pushC2GRPC.proto

package mythicpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Internal transport scheduling metadata. No lane value is serialized into
// agent messages or the Discord transport envelope.
type DeliveryLane int32

const (
	DeliveryLane_STANDARD DeliveryLane = 0
	DeliveryLane_SOCKS    DeliveryLane = 1
)

// Enum value maps for DeliveryLane.
var (
	DeliveryLane_name = map[int32]string{
		0: "STANDARD",
		1: "SOCKS",
	}
	DeliveryLane_value = map[string]int32{
		"STANDARD": 0,
		"SOCKS":    1,
	}
)

func (x DeliveryLane) Enum() *DeliveryLane {
	p := new(DeliveryLane)
	*p = x
	return p
}

func (x DeliveryLane) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryLane) Descriptor() protoreflect.EnumDescriptor {
	return file_pushC2GRPC_proto_enumTypes[0].Descriptor()
}

func (DeliveryLane) Type() protoreflect.EnumType {
	return &file_pushC2GRPC_proto_enumTypes[0]
}

func (x DeliveryLane) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryLane.Descriptor instead.
func (DeliveryLane) EnumDescriptor() ([]byte, []int) {
	return file_pushC2GRPC_proto_rawDescGZIP(), []int{0}
}

// agent sends along the base64 message like normal and c2 profile adds in c2 profile name
// this is all normal c2 profiles pass along to mythic anyway
// C2ProfileName is required
// RemoteIP should be the IP of the remote connection to the c2 profile if known
// Message is a base64 decoded message if you want the c2 profile to base64 decode what the agents are saying
// Base64Message is what an agent would normally send. This is mutually exclusive with Message
// TrackingID is some custom string that the c2 server provides so that it can correlate input with output from the stream
type PushC2MessageFromAgent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	C2ProfileName     string                 `protobuf:"bytes,1,opt,name=C2ProfileName,proto3" json:"C2ProfileName,omitempty"`
	RemoteIP          string                 `protobuf:"bytes,2,opt,name=RemoteIP,proto3" json:"RemoteIP,omitempty"`
	Message           []byte                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	OuterUUID         string                 `protobuf:"bytes,4,opt,name=OuterUUID,proto3" json:"OuterUUID,omitempty"`
	Base64Message     []byte                 `protobuf:"bytes,5,opt,name=Base64Message,proto3" json:"Base64Message,omitempty"`
	TrackingID        string                 `protobuf:"bytes,6,opt,name=TrackingID,proto3" json:"TrackingID,omitempty"`
	AgentDisconnected bool                   `protobuf:"varint,7,opt,name=AgentDisconnected,proto3" json:"AgentDisconnected,omitempty"`
	IngressID         string                 `protobuf:"bytes,8,opt,name=IngressID,proto3" json:"IngressID,omitempty"`
	IngressLane       DeliveryLane           `protobuf:"varint,9,opt,name=IngressLane,proto3,enum=pushC2Services.DeliveryLane" json:"IngressLane,omitempty"`
	OutboundID        string                 `protobuf:"bytes,10,opt,name=OutboundID,proto3" json:"OutboundID,omitempty"`
	IsOutboundReceipt bool                   `protobuf:"varint,11,opt,name=IsOutboundReceipt,proto3" json:"IsOutboundReceipt,omitempty"`
	OutboundSuccess   bool                   `protobuf:"varint,12,opt,name=OutboundSuccess,proto3" json:"OutboundSuccess,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PushC2MessageFromAgent) Reset() {
	*x = PushC2MessageFromAgent{}
	mi := &file_pushC2GRPC_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushC2MessageFromAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushC2MessageFromAgent) ProtoMessage() {}

func (x *PushC2MessageFromAgent) ProtoReflect() protoreflect.Message {
	mi := &file_pushC2GRPC_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushC2MessageFromAgent.ProtoReflect.Descriptor instead.
func (*PushC2MessageFromAgent) Descriptor() ([]byte, []int) {
	return file_pushC2GRPC_proto_rawDescGZIP(), []int{0}
}

func (x *PushC2MessageFromAgent) GetC2ProfileName() string {
	if x != nil {
		return x.C2ProfileName
	}
	return ""
}

func (x *PushC2MessageFromAgent) GetRemoteIP() string {
	if x != nil {
		return x.RemoteIP
	}
	return ""
}

func (x *PushC2MessageFromAgent) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PushC2MessageFromAgent) GetOuterUUID() string {
	if x != nil {
		return x.OuterUUID
	}
	return ""
}

func (x *PushC2MessageFromAgent) GetBase64Message() []byte {
	if x != nil {
		return x.Base64Message
	}
	return nil
}

func (x *PushC2MessageFromAgent) GetTrackingID() string {
	if x != nil {
		return x.TrackingID
	}
	return ""
}

func (x *PushC2MessageFromAgent) GetAgentDisconnected() bool {
	if x != nil {
		return x.AgentDisconnected
	}
	return false
}

func (x *PushC2MessageFromAgent) GetIngressID() string {
	if x != nil {
		return x.IngressID
	}
	return ""
}

func (x *PushC2MessageFromAgent) GetIngressLane() DeliveryLane {
	if x != nil {
		return x.IngressLane
	}
	return DeliveryLane_STANDARD
}

func (x *PushC2MessageFromAgent) GetOutboundID() string {
	if x != nil {
		return x.OutboundID
	}
	return ""
}

func (x *PushC2MessageFromAgent) GetIsOutboundReceipt() bool {
	if x != nil {
		return x.IsOutboundReceipt
	}
	return false
}

func (x *PushC2MessageFromAgent) GetOutboundSuccess() bool {
	if x != nil {
		return x.OutboundSuccess
	}
	return false
}

// mythic sends along success/error information if any
// mythic sends along the messages
type PushC2MessageFromMythic struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Error            string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message          []byte                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	TrackingID       string                 `protobuf:"bytes,4,opt,name=TrackingID,proto3" json:"TrackingID,omitempty"`
	DeliveryLane     DeliveryLane           `protobuf:"varint,5,opt,name=DeliveryLane,proto3,enum=pushC2Services.DeliveryLane" json:"DeliveryLane,omitempty"`
	IngressID        string                 `protobuf:"bytes,6,opt,name=IngressID,proto3" json:"IngressID,omitempty"`
	IsIngressReceipt bool                   `protobuf:"varint,7,opt,name=IsIngressReceipt,proto3" json:"IsIngressReceipt,omitempty"`
	OutboundID       string                 `protobuf:"bytes,8,opt,name=OutboundID,proto3" json:"OutboundID,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PushC2MessageFromMythic) Reset() {
	*x = PushC2MessageFromMythic{}
	mi := &file_pushC2GRPC_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushC2MessageFromMythic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushC2MessageFromMythic) ProtoMessage() {}

func (x *PushC2MessageFromMythic) ProtoReflect() protoreflect.Message {
	mi := &file_pushC2GRPC_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushC2MessageFromMythic.ProtoReflect.Descriptor instead.
func (*PushC2MessageFromMythic) Descriptor() ([]byte, []int) {
	return file_pushC2GRPC_proto_rawDescGZIP(), []int{1}
}

func (x *PushC2MessageFromMythic) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushC2MessageFromMythic) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PushC2MessageFromMythic) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PushC2MessageFromMythic) GetTrackingID() string {
	if x != nil {
		return x.TrackingID
	}
	return ""
}

func (x *PushC2MessageFromMythic) GetDeliveryLane() DeliveryLane {
	if x != nil {
		return x.DeliveryLane
	}
	return DeliveryLane_STANDARD
}

func (x *PushC2MessageFromMythic) GetIngressID() string {
	if x != nil {
		return x.IngressID
	}
	return ""
}

func (x *PushC2MessageFromMythic) GetIsIngressReceipt() bool {
	if x != nil {
		return x.IsIngressReceipt
	}
	return false
}

func (x *PushC2MessageFromMythic) GetOutboundID() string {
	if x != nil {
		return x.OutboundID
	}
	return ""
}

var File_pushC2GRPC_proto protoreflect.FileDescriptor

const file_pushC2GRPC_proto_rawDesc = "" +
	"\n" +
	"\x10pushC2GRPC.proto\x12\x0epushC2Services\"\xdc\x03\n" +
	"\x16PushC2MessageFromAgent\x12$\n" +
	"\rC2ProfileName\x18\x01 \x01(\tR\rC2ProfileName\x12\x1a\n" +
	"\bRemoteIP\x18\x02 \x01(\tR\bRemoteIP\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\fR\aMessage\x12\x1c\n" +
	"\tOuterUUID\x18\x04 \x01(\tR\tOuterUUID\x12$\n" +
	"\rBase64Message\x18\x05 \x01(\fR\rBase64Message\x12\x1e\n" +
	"\n" +
	"TrackingID\x18\x06 \x01(\tR\n" +
	"TrackingID\x12,\n" +
	"\x11AgentDisconnected\x18\a \x01(\bR\x11AgentDisconnected\x12\x1c\n" +
	"\tIngressID\x18\b \x01(\tR\tIngressID\x12>\n" +
	"\vIngressLane\x18\t \x01(\x0e2\x1c.pushC2Services.DeliveryLaneR\vIngressLane\x12\x1e\n" +
	"\n" +
	"OutboundID\x18\n" +
	" \x01(\tR\n" +
	"OutboundID\x12,\n" +
	"\x11IsOutboundReceipt\x18\v \x01(\bR\x11IsOutboundReceipt\x12(\n" +
	"\x0fOutboundSuccess\x18\f \x01(\bR\x0fOutboundSuccess\"\xaf\x02\n" +
	"\x17PushC2MessageFromMythic\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\fR\aMessage\x12\x1e\n" +
	"\n" +
	"TrackingID\x18\x04 \x01(\tR\n" +
	"TrackingID\x12@\n" +
	"\fDeliveryLane\x18\x05 \x01(\x0e2\x1c.pushC2Services.DeliveryLaneR\fDeliveryLane\x12\x1c\n" +
	"\tIngressID\x18\x06 \x01(\tR\tIngressID\x12*\n" +
	"\x10IsIngressReceipt\x18\a \x01(\bR\x10IsIngressReceipt\x12\x1e\n" +
	"\n" +
	"OutboundID\x18\b \x01(\tR\n" +
	"OutboundID*'\n" +
	"\fDeliveryLane\x12\f\n" +
	"\bSTANDARD\x10\x00\x12\t\n" +
	"\x05SOCKS\x10\x012\xef\x01\n" +
	"\x06PushC2\x12m\n" +
	"\x14StartPushC2Streaming\x12&.pushC2Services.PushC2MessageFromAgent\x1a'.pushC2Services.PushC2MessageFromMythic\"\x00(\x010\x01\x12v\n" +
	"\x1dStartPushC2StreamingOneToMany\x12&.pushC2Services.PushC2MessageFromAgent\x1a'.pushC2Services.PushC2MessageFromMythic\"\x00(\x010\x01B/Z-github.com/its-a-feature/Mythic/grpc/servicesb\x06proto3"

var (
	file_pushC2GRPC_proto_rawDescOnce sync.Once
	file_pushC2GRPC_proto_rawDescData []byte
)

func file_pushC2GRPC_proto_rawDescGZIP() []byte {
	file_pushC2GRPC_proto_rawDescOnce.Do(func() {
		file_pushC2GRPC_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pushC2GRPC_proto_rawDesc), len(file_pushC2GRPC_proto_rawDesc)))
	})
	return file_pushC2GRPC_proto_rawDescData
}

var file_pushC2GRPC_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pushC2GRPC_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pushC2GRPC_proto_goTypes = []any{
	(DeliveryLane)(0),               // 0: pushC2Services.DeliveryLane
	(*PushC2MessageFromAgent)(nil),  // 1: pushC2Services.PushC2MessageFromAgent
	(*PushC2MessageFromMythic)(nil), // 2: pushC2Services.PushC2MessageFromMythic
}
var file_pushC2GRPC_proto_depIdxs = []int32{
	0, // 0: pushC2Services.PushC2MessageFromAgent.IngressLane:type_name -> pushC2Services.DeliveryLane
	0, // 1: pushC2Services.PushC2MessageFromMythic.DeliveryLane:type_name -> pushC2Services.DeliveryLane
	1, // 2: pushC2Services.PushC2.StartPushC2Streaming:input_type -> pushC2Services.PushC2MessageFromAgent
	1, // 3: pushC2Services.PushC2.StartPushC2StreamingOneToMany:input_type -> pushC2Services.PushC2MessageFromAgent
	2, // 4: pushC2Services.PushC2.StartPushC2Streaming:output_type -> pushC2Services.PushC2MessageFromMythic
	2, // 5: pushC2Services.PushC2.StartPushC2StreamingOneToMany:output_type -> pushC2Services.PushC2MessageFromMythic
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pushC2GRPC_proto_init() }
func file_pushC2GRPC_proto_init() {
	if File_pushC2GRPC_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pushC2GRPC_proto_rawDesc), len(file_pushC2GRPC_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pushC2GRPC_proto_goTypes,
		DependencyIndexes: file_pushC2GRPC_proto_depIdxs,
		EnumInfos:         file_pushC2GRPC_proto_enumTypes,
		MessageInfos:      file_pushC2GRPC_proto_msgTypes,
	}.Build()
	File_pushC2GRPC_proto = out.File
	file_pushC2GRPC_proto_goTypes = nil
	file_pushC2GRPC_proto_depIdxs = nil
}
